# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84ba27692bb377516053b27d3bdc2460de2af2cf6d6555a2837f04f45e2a31b9b8e3e686820542e27b893c80f2125519f52749bfd9e58da0e835fe1e9203d9cb

test:
  secret_key_base: 6e064142bf42507c387de6d84021aa3858302670a499032ee6d2069d8a7995635f02064476532b1adafd4e1a4538bd774af42f5d3de8fd5aa3ac9aa9d0aca74e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
